# 自动生成的配置文件 - 包含50个GPU芯粒和其他处理器
# Phase 1 configuration.
phase1:
  # Process 0
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["0", "0"]
    log: "gpgpusim.0.0.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 1
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["0", "1"]
    log: "gpgpusim.0.1.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 2
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["0", "2"]
    log: "gpgpusim.0.2.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 3
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["0", "3"]
    log: "gpgpusim.0.3.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 4
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["0", "4"]
    log: "gpgpusim.0.4.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 5
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["1", "0"]
    log: "gpgpusim.1.0.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 6
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["1", "1"]
    log: "gpgpusim.1.1.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 7
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["1", "2"]
    log: "gpgpusim.1.2.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 8
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["1", "3"]
    log: "gpgpusim.1.3.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 9
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["1", "4"]
    log: "gpgpusim.1.4.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 10
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["2", "0"]
    log: "gpgpusim.2.0.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 11
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["2", "1"]
    log: "gpgpusim.2.1.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 12
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["2", "2"]
    log: "gpgpusim.2.2.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 13
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["2", "3"]
    log: "gpgpusim.2.3.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 14
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["2", "4"]
    log: "gpgpusim.2.4.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 15
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["3", "0"]
    log: "gpgpusim.3.0.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 16
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["3", "1"]
    log: "gpgpusim.3.1.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 17
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["3", "2"]
    log: "gpgpusim.3.2.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 18
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["3", "3"]
    log: "gpgpusim.3.3.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 19
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["3", "4"]
    log: "gpgpusim.3.4.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 20
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["4", "0"]
    log: "gpgpusim.4.0.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 21
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["4", "1"]
    log: "gpgpusim.4.1.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 22
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["4", "2"]
    log: "gpgpusim.4.2.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 23
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["4", "3"]
    log: "gpgpusim.4.3.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 24
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["4", "4"]
    log: "gpgpusim.4.4.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 25
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["0", "5"]
    log: "gpgpusim.0.5.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 26
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["0", "6"]
    log: "gpgpusim.0.6.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 27
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["0", "7"]
    log: "gpgpusim.0.7.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 28
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["0", "8"]
    log: "gpgpusim.0.8.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 29
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["0", "9"]
    log: "gpgpusim.0.9.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 30
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["1", "5"]
    log: "gpgpusim.1.5.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 31
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["1", "6"]
    log: "gpgpusim.1.6.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 32
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["1", "7"]
    log: "gpgpusim.1.7.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 33
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["1", "8"]
    log: "gpgpusim.1.8.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 34
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["1", "9"]
    log: "gpgpusim.1.9.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 35
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["2", "5"]
    log: "gpgpusim.2.5.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 36
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["2", "6"]
    log: "gpgpusim.2.6.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 37
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["2", "7"]
    log: "gpgpusim.2.7.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 38
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["2", "8"]
    log: "gpgpusim.2.8.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 39
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["2", "9"]
    log: "gpgpusim.2.9.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 40
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["3", "5"]
    log: "gpgpusim.3.5.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 41
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["3", "6"]
    log: "gpgpusim.3.6.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 42
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["3", "7"]
    log: "gpgpusim.3.7.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 43
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["3", "8"]
    log: "gpgpusim.3.8.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 44
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["3", "9"]
    log: "gpgpusim.3.9.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 45
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["4", "5"]
    log: "gpgpusim.4.5.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 46
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["4", "6"]
    log: "gpgpusim.4.6.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 47
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["4", "7"]
    log: "gpgpusim.4.7.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 48
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["4", "8"]
    log: "gpgpusim.4.8.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 49
  - cmd: "$BENCHMARK_ROOT/bin/mlp_cu"
    args: ["4", "9"]
    log: "gpgpusim.4.9.log"
    is_to_stdout: false
    clock_rate: 1
    pre_copy: "$SIMULATOR_ROOT/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/*"
  # Process 50
  - cmd: "$SIMULATOR_ROOT/snipersim/run-sniper"
    args: ["--", "$BENCHMARK_ROOT/bin/mlp_c", "9", "9"]
    log: "sniper.9.9.log"
    is_to_stdout: false
    clock_rate: 1
  # Process 51
  - cmd: "$BENCHMARK_ROOT/bin/cim"
    args: ["9", "8"]
    log: "npu.9.8.log"
    is_to_stdout: false
    clock_rate: 1
  # Process 52
  - cmd: "$BENCHMARK_ROOT/bin/mnsim"
    args: ["9", "7"]
    log: "mnsim.9.7.log"
    is_to_stdout: false
    clock_rate: 1
# Phase 2 configuration.
phase2:
  # Process 0
  - cmd: "$SIMULATOR_ROOT/popnet_chiplet/build/popnet"
    args: ["-A", "100", "-c", "1", "-V", "3", "-B", "12", "-O", "12", "-F", "2", "-L", "1000", "-T", "1000000000", "-r", "1", "-I", "../bench.txt", "-G", "test/mesh_6_6.gv", "-D", "../delayInfo.txt", "-P"]
    log: "popnet_0.log"
    is_to_stdout: false
    clock_rate: 1

# File configuration. (Not used yet)
bench_file: "./bench_torus_flit_4.txt"
delayinfo_file: "./delayInfo_torus_flit_4.txt"
